/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server identity and capabilities */
        get: operations["getServerIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List media libraries */
        get: operations["getLibrarySections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionId}/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all items in a library */
        get: operations["getLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh a library section */
        post: operations["refreshLibrarySection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get metadata for an item */
        get: operations["getMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get children of an item (e.g., seasons of a show) */
        get: operations["getMetadataChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active playback sessions */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List playlists */
        get: operations["getPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlistId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get items in a playlist */
        get: operations["getPlaylistItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global search across hubs */
        get: operations["searchHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MediaContainer: {
            /** @description Number of items returned */
            size?: number;
            /** @description Total number of items available */
            totalSize?: number;
            /** @description Offset of the current page */
            offset?: number;
            /** @description API identifier, typically 'com.plexapp.plugins.library' */
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            /** @description Primary title for the container */
            title1?: string;
            /** @description Secondary title for the container */
            title2?: string;
            Directory?: components["schemas"]["Directory"][];
            Video?: components["schemas"]["Video"][];
            Track?: components["schemas"]["Track"][];
            Photo?: components["schemas"]["Photo"][];
            Playlist?: components["schemas"]["Playlist"][];
            Hub?: components["schemas"]["Hub"][];
        };
        /** @description Represents a library or collection */
        Directory: {
            key?: string;
            title?: string;
            /** @enum {string} */
            type?: "movie" | "show" | "artist" | "photo";
            uuid?: string;
            updatedAt?: number;
            createdAt?: number;
            scannedAt?: number;
            content?: boolean;
            directory?: boolean;
            hidden?: number;
        };
        /** @description Represents a movie or episode */
        Video: {
            ratingKey?: string;
            key?: string;
            guid?: string;
            /** @enum {string} */
            type?: "movie" | "episode";
            title?: string;
            summary?: string;
            rating?: number;
            year?: number;
            thumb?: string;
            art?: string;
            duration?: number;
            addedAt?: number;
            updatedAt?: number;
            Media?: components["schemas"]["Media"][];
            Genre?: components["schemas"]["Tag"][];
            Director?: components["schemas"]["Tag"][];
            Writer?: components["schemas"]["Tag"][];
            Role?: components["schemas"]["Tag"][];
        };
        /** @description Represents a music track */
        Track: {
            ratingKey?: string;
            key?: string;
            /** @enum {string} */
            type?: "track";
            title?: string;
            index?: number;
            duration?: number;
            Media?: components["schemas"]["Media"][];
        };
        /** @description Represents a photo */
        Photo: {
            ratingKey?: string;
            key?: string;
            /** @enum {string} */
            type?: "photo";
            title?: string;
            summary?: string;
            thumb?: string;
            Media?: components["schemas"]["Media"][];
        };
        /** @description Media container for a metadata item */
        Media: {
            id?: number;
            duration?: number;
            bitrate?: number;
            width?: number;
            height?: number;
            aspectRatio?: number;
            audioChannels?: number;
            audioCodec?: string;
            videoCodec?: string;
            videoResolution?: string;
            container?: string;
            videoFrameRate?: string;
            Part?: components["schemas"]["Part"][];
        };
        /** @description A media part (file) */
        Part: {
            id?: number;
            key?: string;
            duration?: number;
            file?: string;
            size?: number;
            container?: string;
            videoProfile?: string;
        };
        /** @description A tag such as genre, director, actor, etc. */
        Tag: {
            tag?: string;
            id?: number;
        };
        /** @description Represents a playlist */
        Playlist: {
            ratingKey?: string;
            key?: string;
            title?: string;
            /** @enum {string} */
            type?: "playlist";
            /** @enum {string} */
            playlistType?: "video" | "audio" | "photo";
            summary?: string;
            smart?: boolean;
            leafCount?: number;
            addedAt?: number;
            updatedAt?: number;
        };
        /** @description Search result hub */
        Hub: {
            key?: string;
            title?: string;
            type?: string;
            hubIdentifier?: string;
            context?: string;
            size?: number;
            Video?: components["schemas"]["Video"][];
            Directory?: components["schemas"]["Directory"][];
        };
    };
    responses: never;
    parameters: {
        /** @description Library section identifier */
        sectionId: number;
        /** @description Unique metadata rating key */
        ratingKey: number;
        /** @description Playlist identifier */
        playlistId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getServerIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    getLibrarySections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    getLibraryItems: {
        parameters: {
            query?: {
                /** @description Filter by media type (1 = movie, 2 = show, 8 = artist, etc.) */
                type?: number;
            };
            header?: {
                /** @description Page size */
                "X-Plex-Container-Size"?: number;
                /** @description Page offset */
                "X-Plex-Container-Start"?: number;
            };
            path: {
                /** @description Library section identifier */
                sectionId: components["parameters"]["sectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    refreshLibrarySection: {
        parameters: {
            query?: {
                /** @description Force metadata refresh */
                force?: 0 | 1;
            };
            header?: never;
            path: {
                /** @description Library section identifier */
                sectionId: components["parameters"]["sectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique metadata rating key */
                ratingKey: components["parameters"]["ratingKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    getMetadataChildren: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique metadata rating key */
                ratingKey: components["parameters"]["ratingKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Child items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    getPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    getPlaylistItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist identifier */
                playlistId: components["parameters"]["playlistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
    searchHubs: {
        parameters: {
            query: {
                /** @description Search query */
                query: string;
                /** @description Maximum results per hub */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results grouped by hub */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainer"];
                    "application/xml": components["schemas"]["MediaContainer"];
                };
            };
        };
    };
}
