/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server identity
         * @description Returns the server's identity, including its unique Machine Identifier. This endpoint does not require authentication and is commonly used for server discovery.
         */
        get: operations["getIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server information
         * @description Returns the server root MediaContainer, including friendly name, platform, version, and available features.
         */
        get: operations["getServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List library sections
         * @description Returns all configured library sections (movies, TV shows, music, photos, etc.).
         */
        get: operations["getLibrarySections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List items in a library section
         * @description Returns all items within a specific library section. Use query parameters such as `type` and `includeCollections` to narrow results.
         */
        get: operations["getLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a library section
         * @description Triggers a metadata refresh for the specified library section.
         */
        post: operations["refreshLibrarySection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search within a library section
         * @description Returns search results scoped to a single library section.
         */
        get: operations["searchLibrarySection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata for an item
         * @description Returns full metadata for a single item by its rating key.
         */
        get: operations["getMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get children of an item
         * @description Returns child items for a metadata object, such as seasons of a show or episodes of a season.
         */
        get: operations["getMetadataChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description Returns currently active playback sessions, including player state, user, and media being played.
         */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List playlists
         * @description Returns all playlists for the authenticated user.
         */
        get: operations["getPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlistKey}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get playlist items
         * @description Returns the items contained in a playlist.
         */
        get: operations["getPlaylistItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global search across hubs
         * @description Returns search results grouped by hub across all libraries.
         */
        get: operations["searchHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Root wrapper for identity responses. */
        MediaContainerIdentity: {
            MediaContainer?: components["schemas"]["Identity"];
        };
        /** @description Server identity details. */
        Identity: {
            size?: number;
            claimed?: boolean;
            /** @description Unique machine identifier for this server. */
            machineIdentifier?: string;
            version?: string;
        };
        /** @description Root wrapper for server root responses. */
        MediaContainerServer: {
            MediaContainer?: components["schemas"]["ServerInfo"];
        };
        /** @description Server-level status and capabilities. */
        ServerInfo: {
            size?: number;
            allowCameraUpload?: boolean;
            allowMediaDeletion?: boolean;
            allowSharing?: boolean;
            allowSync?: boolean;
            backgroundProcessing?: boolean;
            certificate?: boolean;
            companionProxy?: boolean;
            countryCode?: string;
            diagnostics?: string;
            eventSource?: boolean;
            friendlyName?: string;
            livetv?: number;
            machineIdentifier?: string;
            myPlex?: boolean;
            myPlexMappingState?: string;
            myPlexSigninState?: string;
            myPlexSubscription?: boolean;
            myPlexUsername?: string;
            offlineTranscode?: number;
            ownerFeatures?: string;
            photoAutoTag?: boolean;
            platform?: string;
            platformVersion?: string;
            pluginHost?: boolean;
            pushNotifications?: boolean;
            readOnlyLibraries?: boolean;
            streamingBrainVersion?: number;
            sync?: boolean;
            transcoderActiveVideoSessions?: number;
            transcoderAudio?: boolean;
            transcoderLyrics?: boolean;
            transcoderPhoto?: boolean;
            transcoderSubtitles?: boolean;
            transcoderVideo?: boolean;
            /** @description Unix timestamp of the last server update. */
            updatedAt?: number;
            updater?: boolean;
            version?: string;
            voiceSearch?: boolean;
            Directory?: components["schemas"]["ServerCapability"][];
        };
        /** @description A capability or service exposed by the server root. */
        ServerCapability: {
            count?: number;
            key?: string;
            title?: string;
        };
        /** @description Root wrapper for library section listings. */
        MediaContainerLibrarySections: {
            MediaContainer?: components["schemas"]["LibrarySections"];
        };
        /** @description Collection of library sections. */
        LibrarySections: {
            size?: number;
            allowSync?: boolean;
            art?: string;
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            Directory?: components["schemas"]["LibrarySection"][];
        };
        /** @description A single library section (movie, show, artist, photo). */
        LibrarySection: {
            allowSync?: boolean;
            art?: string;
            composite?: string;
            filters?: boolean;
            refreshing?: boolean;
            thumb?: string;
            /** @enum {string} */
            type?: "movie" | "show" | "artist" | "photo";
            title?: string;
            agent?: string;
            scanner?: string;
            language?: string;
            uuid?: string;
            updatedAt?: number;
            createdAt?: number;
            scannedAt?: number;
            content?: boolean;
            directory?: boolean;
            contentChangedAt?: number;
            hidden?: number;
            Location?: components["schemas"]["LibrarySectionLocation"][];
        };
        /** @description Filesystem location backing a library section. */
        LibrarySectionLocation: {
            id?: number;
            path?: string;
        };
        /** @description Root wrapper for library item listings. */
        MediaContainerLibraryItems: {
            MediaContainer?: components["schemas"]["LibraryItems"];
        };
        /** @description Collection of items within a library section. */
        LibraryItems: {
            size?: number;
            allowSync?: boolean;
            art?: string;
            identifier?: string;
            librarySectionID?: number;
            librarySectionTitle?: string;
            librarySectionUUID?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            nocache?: boolean;
            offset?: number;
            totalSize?: number;
            title1?: string;
            title2?: string;
            viewGroup?: string;
            viewMode?: number;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Base fields common to movies, episodes, tracks, and photos. */
        MediaItem: {
            ratingKey?: string;
            key?: string;
            parentRatingKey?: string;
            grandparentRatingKey?: string;
            guid?: string;
            parentGuid?: string;
            grandparentGuid?: string;
            /** @enum {string} */
            type?: "movie" | "show" | "season" | "episode" | "artist" | "album" | "track" | "photo" | "photoalbum";
            title?: string;
            titleSort?: string;
            summary?: string;
            thumb?: string;
            art?: string;
            banner?: string;
            theme?: string;
            duration?: number;
            addedAt?: number;
            updatedAt?: number;
            /** Format: date */
            originallyAvailableAt?: string;
            rating?: number;
            userRating?: number;
            viewCount?: number;
            lastViewedAt?: number;
            year?: number;
            studio?: string;
            tagline?: string;
            contentRating?: string;
            audienceRating?: number;
            audienceRatingImage?: string;
            chapterSource?: string;
            primaryExtraKey?: string;
            Media?: components["schemas"]["Media"][];
            Genre?: components["schemas"]["Tag"][];
            Director?: components["schemas"]["Tag"][];
            Writer?: components["schemas"]["Tag"][];
            Role?: components["schemas"]["Tag"][];
        };
        /** @description Media container describing one or more file parts for a metadata item. */
        Media: {
            id?: number;
            duration?: number;
            bitrate?: number;
            width?: number;
            height?: number;
            aspectRatio?: number;
            audioChannels?: number;
            audioCodec?: string;
            videoCodec?: string;
            videoResolution?: string;
            container?: string;
            videoFrameRate?: string;
            Part?: components["schemas"]["Part"][];
        };
        /** @description A single media file part. */
        Part: {
            id?: number;
            key?: string;
            duration?: number;
            file?: string;
            size?: number;
            container?: string;
            videoProfile?: string;
        };
        /** @description A tag such as a genre, director, writer, or actor. */
        Tag: {
            tag?: string;
            id?: number;
        };
        /** @description Root wrapper for a single metadata item response. */
        MediaContainerMetadata: {
            MediaContainer?: components["schemas"]["MetadataItem"];
        };
        /** @description A single metadata item wrapper. */
        MetadataItem: {
            size?: number;
            allowSync?: boolean;
            identifier?: string;
            librarySectionID?: number;
            librarySectionTitle?: string;
            librarySectionUUID?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for metadata child item listings. */
        MediaContainerMetadataChildren: {
            MediaContainer?: components["schemas"]["MetadataChildren"];
        };
        /** @description Collection of child metadata items. */
        MetadataChildren: {
            size?: number;
            totalSize?: number;
            offset?: number;
            identifier?: string;
            librarySectionID?: number;
            librarySectionTitle?: string;
            librarySectionUUID?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            viewGroup?: string;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for playlist listings. */
        MediaContainerPlaylists: {
            MediaContainer?: components["schemas"]["Playlists"];
        };
        /** @description Collection of playlists. */
        Playlists: {
            size?: number;
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            Metadata?: components["schemas"]["Playlist"][];
        };
        /** @description A single playlist. */
        Playlist: {
            ratingKey?: string;
            key?: string;
            title?: string;
            /** @enum {string} */
            type?: "playlist";
            /** @enum {string} */
            playlistType?: "video" | "audio" | "photo";
            summary?: string;
            smart?: boolean;
            leafCount?: number;
            addedAt?: number;
            updatedAt?: number;
        };
        /** @description Root wrapper for playlist item listings. */
        MediaContainerPlaylistItems: {
            MediaContainer?: components["schemas"]["PlaylistItems"];
        };
        /** @description Collection of items in a playlist. */
        PlaylistItems: {
            size?: number;
            totalSize?: number;
            offset?: number;
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for hub/search results. */
        MediaContainerHub: {
            MediaContainer?: components["schemas"]["Hub"];
        };
        /** @description Collection of search hubs. */
        Hub: {
            size?: number;
            identifier?: string;
            title1?: string;
            title2?: string;
            Hub?: components["schemas"]["HubEntry"][];
        };
        /** @description A single hub grouping within a search response. */
        HubEntry: {
            key?: string;
            title?: string;
            type?: string;
            hubIdentifier?: string;
            context?: string;
            size?: number;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for active session listings. */
        MediaContainerSessions: {
            MediaContainer?: components["schemas"]["Sessions"];
        };
        /** @description Collection of active playback sessions. */
        Sessions: {
            size?: number;
            Metadata?: components["schemas"]["Session"][];
        };
        /** @description An active playback session, extending a media item with player and session details. */
        Session: components["schemas"]["MediaItem"] & {
            Session?: {
                id?: string;
                bandwidth?: number;
                location?: string;
                data?: string;
            };
            Player?: {
                address?: string;
                device?: string;
                machineIdentifier?: string;
                model?: string;
                platform?: string;
                platformVersion?: string;
                product?: string;
                profile?: string;
                remotePublicAddress?: string;
                /** @enum {string} */
                state?: "playing" | "paused" | "buffering" | "stopped";
                title?: string;
                userID?: string;
                vendor?: string;
                version?: string;
                local?: boolean;
                relayed?: boolean;
                secure?: boolean;
                throttled?: boolean;
            };
            User?: {
                id?: string;
                title?: string;
                thumb?: string;
            };
            TranscodeSession?: {
                key?: string;
                throttled?: boolean;
                complete?: boolean;
                progress?: number;
                size?: number;
                speed?: number;
                error?: boolean;
                duration?: number;
                context?: string;
                sourceVideoCodec?: string;
                sourceAudioCodec?: string;
                videoDecision?: string;
                audioDecision?: string;
                protocol?: string;
                container?: string;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
        AcceptHeader: "application/json" | "application/xml";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIdentity: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerIdentity"];
                };
            };
        };
    };
    getServerInfo: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerServer"];
                };
            };
        };
    };
    getLibrarySections: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library sections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibrarySections"];
                };
            };
        };
    };
    getLibraryItems: {
        parameters: {
            query?: {
                /** @description Filter by media type integer (e.g., 1 for movies, 2 for shows, 8 for artists). */
                type?: number;
                /** @description Include collection items in the response. */
                includeCollections?: 0 | 1;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section, as returned by `/library/sections`. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    refreshLibrarySection: {
        parameters: {
            query?: {
                /** @description Force a full metadata refresh. */
                force?: 0 | 1;
            };
            header?: never;
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchLibrarySection: {
        parameters: {
            query: {
                /** @description Search query string. */
                query: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Section search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
    getMetadata: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerMetadata"];
                };
            };
        };
    };
    getMetadataChildren: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the parent item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Child items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerMetadataChildren"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerSessions"];
                };
            };
        };
    };
    getPlaylists: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylists"];
                };
            };
        };
    };
    getPlaylistItems: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the playlist. */
                playlistKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylistItems"];
                };
            };
        };
    };
    searchHubs: {
        parameters: {
            query: {
                /** @description Search query string. */
                query: string;
                /** @description Maximum results per hub. */
                limit?: number;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
}
