/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server identity
         * @description Returns the server's identity, including its unique Machine Identifier. This endpoint does not require authentication and is commonly used for server discovery.
         */
        get: operations["getIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server information
         * @description Returns the server root MediaContainer, including friendly name, platform, version, and available features.
         */
        get: operations["getServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List library sections
         * @description Returns all configured library sections (movies, TV shows, music, photos, etc.).
         */
        get: operations["getLibrarySections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List items in a library section
         * @description Returns all items within a specific library section. Use query parameters such as `type` and `includeCollections` to narrow results.
         */
        get: operations["getLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a library section
         * @description Triggers a metadata refresh for the specified library section.
         */
        post: operations["refreshLibrarySection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search within a library section
         * @description Returns search results scoped to a single library section.
         */
        get: operations["searchLibrarySection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata for an item
         * @description Returns full metadata for a single item by its rating key.
         */
        get: operations["getMetadata"];
        /**
         * Update metadata
         * @description Updates metadata fields for an item.
         */
        put: operations["updateMetadata"];
        post?: never;
        /**
         * Delete metadata item
         * @description Removes a metadata item from the library.
         */
        delete: operations["deleteMetadata"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get children of an item
         * @description Returns child items for a metadata object, such as seasons of a show or episodes of a season.
         */
        get: operations["getMetadataChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description Returns currently active playback sessions, including player state, user, and media being played.
         */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List playlists
         * @description Returns all playlists for the authenticated user.
         */
        get: operations["getPlaylists"];
        put?: never;
        /**
         * Create playlist
         * @description Creates a new playlist.
         */
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlistKey}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get playlist items
         * @description Returns the items contained in a playlist.
         */
        get: operations["getPlaylistItems"];
        put?: never;
        /**
         * Add items to playlist
         * @description Adds items to a playlist.
         */
        post: operations["addPlaylistItems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global search across hubs
         * @description Returns search results grouped by hub across all libraries.
         */
        get: operations["searchHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/myplex/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plex account
         * @description Returns the Plex.tv account associated with the server.
         */
        get: operations["getMyPlexAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List managed accounts
         * @description Returns managed accounts configured on the server.
         */
        get: operations["getAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server preferences
         * @description Returns server preference settings.
         */
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send system notification
         * @description Sends a system notification to connected clients.
         */
        post: operations["sendSystemNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server statistics
         * @description Returns server usage statistics.
         */
        get: operations["getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/sessions/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session history
         * @description Returns historical playback sessions.
         */
        get: operations["getSessionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/sessions/{sessionKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Terminate a session
         * @description Stops an active playback session.
         */
        delete: operations["terminateSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/onDeck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get global on deck
         * @description Returns recently added, in-progress content across all libraries.
         */
        get: operations["getOnDeck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/recentlyAdded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recently added
         * @description Returns recently added items across all libraries.
         */
        get: operations["getRecentlyAdded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List library collections
         * @description Returns collections within a library section.
         */
        get: operations["getLibraryCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/newest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get newest library items
         * @description Returns newest items added to a library section.
         */
        get: operations["getLibraryNewest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/unwatched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unwatched library items
         * @description Returns unwatched items in a library section.
         */
        get: operations["getLibraryUnwatched"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse library folder
         * @description Returns folder-based browsing results for a library section.
         */
        get: operations["getLibraryFolder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/firstCharacter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get first-character groups
         * @description Returns first-character groupings for a library section.
         */
        get: operations["getLibraryFirstCharacter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get library section preferences
         * @description Returns preferences for a library section.
         */
        get: operations["getLibrarySectionPreferences"];
        /**
         * Set library section preferences
         * @description Updates preferences for a library section.
         */
        put: operations["setLibrarySectionPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/onDeck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get section on deck
         * @description Returns on-deck items for a library section.
         */
        get: operations["getSectionOnDeck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}/recentlyAdded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get section recently added
         * @description Returns recently added items for a library section.
         */
        get: operations["getSectionRecentlyAdded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sections/{sectionKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a library section
         * @description Removes a library section from the server.
         */
        delete: operations["deleteLibrarySection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata tree
         * @description Returns the full ancestor/descendant tree for a metadata item.
         */
        get: operations["getMetadataTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/posters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata posters
         * @description Returns available poster images for a metadata item.
         */
        get: operations["getMetadataPosters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/arts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata arts
         * @description Returns available background art for a metadata item.
         */
        get: operations["getMetadataArts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get similar items
         * @description Returns items similar to the given metadata item.
         */
        get: operations["getMetadataSimilar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/metadata/{ratingKey}/banner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata banner
         * @description Returns the banner image for a metadata item.
         */
        get: operations["getMetadataBanner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/parts/{partKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media part details
         * @description Returns details for a specific media part.
         */
        get: operations["getLibraryPart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlistKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update playlist
         * @description Updates playlist metadata.
         */
        put: operations["updatePlaylist"];
        post?: never;
        /**
         * Delete playlist
         * @description Deletes a playlist.
         */
        delete: operations["deletePlaylist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlistKey}/items/{itemKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove item from playlist
         * @description Removes an item from a playlist.
         */
        delete: operations["removePlaylistItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/sections/{sectionKey}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search within a section hub
         * @description Returns hub search results scoped to a library section.
         */
        get: operations["searchSectionHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/promoted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get promoted hubs
         * @description Returns promoted hub content.
         */
        get: operations["getPromotedHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get home hubs
         * @description Returns home screen hub content.
         */
        get: operations["getHomeHubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photo/:/transcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transcode a photo
         * @description Returns a transcoded photo asset.
         */
        get: operations["transcodePhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/:/transcode/universal/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transcode decision
         * @description Returns a playback transcode decision.
         */
        get: operations["getTranscodeDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/:/transcode/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transcode session
         * @description Returns details for an active transcode session.
         */
        get: operations["getTranscodeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/:/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post playback timeline
         * @description Reports playback progress to the server.
         */
        post: operations["postTimeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/:/scrobble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scrobble item
         * @description Marks an item as watched.
         */
        post: operations["scrobble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/:/unscrobble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unscrobble item
         * @description Marks an item as unwatched.
         */
        post: operations["unscrobble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/:/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post viewing progress
         * @description Updates viewing progress for an item.
         */
        post: operations["postProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sync items
         * @description Returns configured sync items.
         */
        get: operations["getSyncItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh sync
         * @description Triggers a refresh of sync items.
         */
        post: operations["refreshSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Root wrapper for identity responses. */
        MediaContainerIdentity: {
            MediaContainer?: components["schemas"]["Identity"];
        };
        /** @description Server identity details. */
        Identity: {
            size?: number;
            claimed?: boolean;
            /** @description Unique machine identifier for this server. */
            machineIdentifier?: string;
            version?: string;
        };
        /** @description Root wrapper for server root responses. */
        MediaContainerServer: {
            MediaContainer?: components["schemas"]["ServerInfo"];
        };
        /** @description Server-level status and capabilities. */
        ServerInfo: {
            size?: number;
            allowCameraUpload?: boolean;
            allowMediaDeletion?: boolean;
            allowSharing?: boolean;
            allowSync?: boolean;
            backgroundProcessing?: boolean;
            certificate?: boolean;
            companionProxy?: boolean;
            countryCode?: string;
            diagnostics?: string;
            eventSource?: boolean;
            friendlyName?: string;
            livetv?: number;
            machineIdentifier?: string;
            myPlex?: boolean;
            myPlexMappingState?: string;
            myPlexSigninState?: string;
            myPlexSubscription?: boolean;
            myPlexUsername?: string;
            offlineTranscode?: number;
            ownerFeatures?: string;
            photoAutoTag?: boolean;
            platform?: string;
            platformVersion?: string;
            pluginHost?: boolean;
            pushNotifications?: boolean;
            readOnlyLibraries?: boolean;
            streamingBrainVersion?: number;
            sync?: boolean;
            transcoderActiveVideoSessions?: number;
            transcoderAudio?: boolean;
            transcoderLyrics?: boolean;
            transcoderPhoto?: boolean;
            transcoderSubtitles?: boolean;
            transcoderVideo?: boolean;
            /** @description Unix timestamp of the last server update. */
            updatedAt?: number;
            updater?: boolean;
            version?: string;
            voiceSearch?: boolean;
            Directory?: components["schemas"]["ServerCapability"][];
        };
        /** @description A capability or service exposed by the server root. */
        ServerCapability: {
            count?: number;
            key?: string;
            title?: string;
        };
        /** @description Root wrapper for library section listings. */
        MediaContainerLibrarySections: {
            MediaContainer?: components["schemas"]["LibrarySections"];
        };
        /** @description Collection of library sections. */
        LibrarySections: {
            size?: number;
            allowSync?: boolean;
            art?: string;
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            Directory?: components["schemas"]["LibrarySection"][];
        };
        /** @description A single library section (movie, show, artist, photo). */
        LibrarySection: {
            allowSync?: boolean;
            art?: string;
            composite?: string;
            filters?: boolean;
            refreshing?: boolean;
            thumb?: string;
            /** @enum {string} */
            type?: "movie" | "show" | "artist" | "photo";
            title?: string;
            agent?: string;
            scanner?: string;
            language?: string;
            uuid?: string;
            updatedAt?: number;
            createdAt?: number;
            scannedAt?: number;
            content?: boolean;
            directory?: boolean;
            contentChangedAt?: number;
            hidden?: number;
            Location?: components["schemas"]["LibrarySectionLocation"][];
        };
        /** @description Filesystem location backing a library section. */
        LibrarySectionLocation: {
            id?: number;
            path?: string;
        };
        /** @description Root wrapper for library item listings. */
        MediaContainerLibraryItems: {
            MediaContainer?: components["schemas"]["LibraryItems"];
        };
        /** @description Collection of items within a library section. */
        LibraryItems: {
            size?: number;
            allowSync?: boolean;
            art?: string;
            identifier?: string;
            librarySectionID?: number;
            librarySectionTitle?: string;
            librarySectionUUID?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            nocache?: boolean;
            offset?: number;
            totalSize?: number;
            title1?: string;
            title2?: string;
            viewGroup?: string;
            viewMode?: number;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Base fields common to movies, episodes, tracks, and photos. */
        MediaItem: {
            ratingKey?: string;
            key?: string;
            parentRatingKey?: string;
            grandparentRatingKey?: string;
            guid?: string;
            parentGuid?: string;
            grandparentGuid?: string;
            /** @enum {string} */
            type?: "movie" | "show" | "season" | "episode" | "artist" | "album" | "track" | "photo" | "photoalbum";
            title?: string;
            titleSort?: string;
            summary?: string;
            thumb?: string;
            art?: string;
            banner?: string;
            theme?: string;
            duration?: number;
            addedAt?: number;
            updatedAt?: number;
            /** Format: date */
            originallyAvailableAt?: string;
            rating?: number;
            userRating?: number;
            viewCount?: number;
            lastViewedAt?: number;
            year?: number;
            studio?: string;
            tagline?: string;
            contentRating?: string;
            audienceRating?: number;
            audienceRatingImage?: string;
            chapterSource?: string;
            primaryExtraKey?: string;
            Media?: components["schemas"]["Media"][];
            Genre?: components["schemas"]["Tag"][];
            Director?: components["schemas"]["Tag"][];
            Writer?: components["schemas"]["Tag"][];
            Role?: components["schemas"]["Tag"][];
        };
        /** @description Media container describing one or more file parts for a metadata item. */
        Media: {
            id?: number;
            duration?: number;
            bitrate?: number;
            width?: number;
            height?: number;
            aspectRatio?: number;
            audioChannels?: number;
            audioCodec?: string;
            videoCodec?: string;
            videoResolution?: string;
            container?: string;
            videoFrameRate?: string;
            Part?: components["schemas"]["Part"][];
        };
        /** @description A single media file part. */
        Part: {
            id?: number;
            key?: string;
            duration?: number;
            file?: string;
            size?: number;
            container?: string;
            videoProfile?: string;
        };
        /** @description A tag such as a genre, director, writer, or actor. */
        Tag: {
            tag?: string;
            id?: number;
        };
        /** @description Root wrapper for a single metadata item response. */
        MediaContainerMetadata: {
            MediaContainer?: components["schemas"]["MetadataItem"];
        };
        /** @description A single metadata item wrapper. */
        MetadataItem: {
            size?: number;
            allowSync?: boolean;
            identifier?: string;
            librarySectionID?: number;
            librarySectionTitle?: string;
            librarySectionUUID?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for metadata child item listings. */
        MediaContainerMetadataChildren: {
            MediaContainer?: components["schemas"]["MetadataChildren"];
        };
        /** @description Collection of child metadata items. */
        MetadataChildren: {
            size?: number;
            totalSize?: number;
            offset?: number;
            identifier?: string;
            librarySectionID?: number;
            librarySectionTitle?: string;
            librarySectionUUID?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            viewGroup?: string;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for playlist listings. */
        MediaContainerPlaylists: {
            MediaContainer?: components["schemas"]["Playlists"];
        };
        /** @description Collection of playlists. */
        Playlists: {
            size?: number;
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            Metadata?: components["schemas"]["Playlist"][];
        };
        /** @description A single playlist. */
        Playlist: {
            ratingKey?: string;
            key?: string;
            title?: string;
            /** @enum {string} */
            type?: "playlist";
            /** @enum {string} */
            playlistType?: "video" | "audio" | "photo";
            summary?: string;
            smart?: boolean;
            leafCount?: number;
            addedAt?: number;
            updatedAt?: number;
        };
        /** @description Root wrapper for playlist item listings. */
        MediaContainerPlaylistItems: {
            MediaContainer?: components["schemas"]["PlaylistItems"];
        };
        /** @description Collection of items in a playlist. */
        PlaylistItems: {
            size?: number;
            totalSize?: number;
            offset?: number;
            identifier?: string;
            mediaTagPrefix?: string;
            mediaTagVersion?: number;
            title1?: string;
            title2?: string;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for hub/search results. */
        MediaContainerHub: {
            MediaContainer?: components["schemas"]["Hub"];
        };
        /** @description Collection of search hubs. */
        Hub: {
            size?: number;
            identifier?: string;
            title1?: string;
            title2?: string;
            Hub?: components["schemas"]["HubEntry"][];
        };
        /** @description A single hub grouping within a search response. */
        HubEntry: {
            key?: string;
            title?: string;
            type?: string;
            hubIdentifier?: string;
            context?: string;
            size?: number;
            Metadata?: components["schemas"]["MediaItem"][];
        };
        /** @description Root wrapper for active session listings. */
        MediaContainerSessions: {
            MediaContainer?: components["schemas"]["Sessions"];
        };
        /** @description Collection of active playback sessions. */
        Sessions: {
            size?: number;
            Metadata?: components["schemas"]["Session"][];
        };
        /** @description An active playback session, extending a media item with player and session details. */
        Session: components["schemas"]["MediaItem"] & {
            Session?: {
                id?: string;
                bandwidth?: number;
                location?: string;
                data?: string;
            };
            Player?: {
                address?: string;
                device?: string;
                machineIdentifier?: string;
                model?: string;
                platform?: string;
                platformVersion?: string;
                product?: string;
                profile?: string;
                remotePublicAddress?: string;
                /** @enum {string} */
                state?: "playing" | "paused" | "buffering" | "stopped";
                title?: string;
                userID?: string;
                vendor?: string;
                version?: string;
                local?: boolean;
                relayed?: boolean;
                secure?: boolean;
                throttled?: boolean;
            };
            User?: {
                id?: string;
                title?: string;
                thumb?: string;
            };
            TranscodeSession?: {
                key?: string;
                throttled?: boolean;
                complete?: boolean;
                progress?: number;
                size?: number;
                speed?: number;
                error?: boolean;
                duration?: number;
                context?: string;
                sourceVideoCodec?: string;
                sourceAudioCodec?: string;
                videoDecision?: string;
                audioDecision?: string;
                protocol?: string;
                container?: string;
            };
        };
        /** @description Root wrapper for Plex account response. */
        MediaContainerAccount: {
            MediaContainer?: components["schemas"]["PlexAccount"];
        };
        /** @description Plex.tv account details. */
        PlexAccount: {
            size?: number;
            email?: string;
            username?: string;
            thumb?: string;
            home?: boolean;
            guest?: boolean;
            queueEmail?: string;
        };
        /** @description Root wrapper for managed accounts response. */
        MediaContainerAccounts: {
            MediaContainer?: components["schemas"]["Accounts"];
        };
        /** @description Collection of managed accounts. */
        Accounts: {
            size?: number;
            Account?: components["schemas"]["Account"][];
        };
        /** @description A managed account. */
        Account: {
            id?: number;
            key?: string;
            name?: string;
            defaultAudioLanguage?: string;
            defaultSubtitleLanguage?: string;
        };
        /** @description Root wrapper for preferences response. */
        MediaContainerPreferences: {
            MediaContainer?: components["schemas"]["Preferences"];
        };
        /** @description Collection of server or section preferences. */
        Preferences: {
            size?: number;
            Setting?: components["schemas"]["Setting"][];
        };
        /** @description A single preference setting. */
        Setting: {
            id?: string;
            label?: string;
            summary?: string;
            type?: string;
            default?: unknown;
            value?: unknown;
            hidden?: boolean;
            advanced?: boolean;
        };
        /** @description Root wrapper for server statistics. */
        MediaContainerStatistics: {
            MediaContainer?: components["schemas"]["Statistics"];
        };
        /** @description Server statistics container. */
        Statistics: {
            size?: number;
            Account?: components["schemas"]["StatisticsAccount"][];
        };
        /** @description Per-account playback statistics. */
        StatisticsAccount: {
            accountID?: number;
            Device?: components["schemas"]["StatisticsDevice"][];
        };
        /** @description Per-device playback statistics. */
        StatisticsDevice: {
            deviceName?: string;
            lastPlayedAt?: number;
            totalPlays?: number;
        };
        /** @description Root wrapper for session history. */
        MediaContainerSessionHistory: {
            MediaContainer?: components["schemas"]["SessionHistory"];
        };
        /** @description Collection of historical playback sessions. */
        SessionHistory: {
            size?: number;
            totalSize?: number;
            offset?: number;
            Metadata?: components["schemas"]["SessionHistoryEntry"][];
        };
        /** @description A single historical playback session. */
        SessionHistoryEntry: {
            ratingKey?: string;
            key?: string;
            parentRatingKey?: string;
            grandparentRatingKey?: string;
            title?: string;
            type?: string;
            thumb?: string;
            viewedAt?: number;
            accountID?: number;
            deviceID?: number;
        };
        /** @description Root wrapper for available images. */
        MediaContainerImages: {
            MediaContainer?: components["schemas"]["Images"];
        };
        /** @description Collection of available images. */
        Images: {
            size?: number;
            Photo?: components["schemas"]["Image"][];
        };
        /** @description An image asset. */
        Image: {
            key?: string;
            ratingKey?: string;
            selected?: boolean;
            thumb?: string;
        };
        /** @description Root wrapper for media parts. */
        MediaContainerParts: {
            MediaContainer?: components["schemas"]["Parts"];
        };
        /** @description Collection of media parts. */
        Parts: {
            size?: number;
            Metadata?: components["schemas"]["Part"][];
        };
        /** @description Root wrapper for a transcode decision. */
        MediaContainerTranscodeDecision: {
            MediaContainer?: components["schemas"]["TranscodeDecision"];
        };
        /** @description Playback transcode decision. */
        TranscodeDecision: {
            size?: number;
            canDirectPlay?: boolean;
            canDirectStream?: boolean;
            canTranscode?: boolean;
            transcodeContainer?: string;
            transcodeVideoCodec?: string;
            transcodeAudioCodec?: string;
            transcodeProtocol?: string;
        };
        /** @description Root wrapper for transcode session details. */
        MediaContainerTranscodeSession: {
            MediaContainer?: components["schemas"]["TranscodeSession"];
        };
        /** @description Details of an active transcode session. */
        TranscodeSession: {
            key?: string;
            throttled?: boolean;
            complete?: boolean;
            progress?: number;
            size?: number;
            speed?: number;
            error?: boolean;
            duration?: number;
            context?: string;
            sourceVideoCodec?: string;
            sourceAudioCodec?: string;
            videoDecision?: string;
            audioDecision?: string;
            protocol?: string;
            container?: string;
        };
        /** @description Root wrapper for sync items. */
        MediaContainerSyncItems: {
            MediaContainer?: components["schemas"]["SyncItems"];
        };
        /** @description Collection of sync items. */
        SyncItems: {
            size?: number;
            SyncItem?: components["schemas"]["SyncItem"][];
        };
        /** @description A sync item. */
        SyncItem: {
            id?: number;
            version?: number;
            rootTitle?: string;
            title?: string;
            status?: string;
            downloadState?: string[];
        };
    };
    responses: never;
    parameters: {
        /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
        AcceptHeader: "application/json" | "application/xml";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIdentity: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerIdentity"];
                };
            };
        };
    };
    getServerInfo: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerServer"];
                };
            };
        };
    };
    getLibrarySections: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library sections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibrarySections"];
                };
            };
        };
    };
    getLibraryItems: {
        parameters: {
            query?: {
                /** @description Filter by media type integer (e.g., 1 for movies, 2 for shows, 8 for artists). */
                type?: number;
                /** @description Include collection items in the response. */
                includeCollections?: 0 | 1;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section, as returned by `/library/sections`. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    refreshLibrarySection: {
        parameters: {
            query?: {
                /** @description Force a full metadata refresh. */
                force?: 0 | 1;
            };
            header?: never;
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchLibrarySection: {
        parameters: {
            query: {
                /** @description Search query string. */
                query: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Section search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
    getMetadata: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerMetadata"];
                };
            };
        };
    };
    updateMetadata: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerMetadata"];
                };
            };
        };
    };
    deleteMetadata: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata item deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMetadataChildren: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the parent item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Child items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerMetadataChildren"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerSessions"];
                };
            };
        };
    };
    getPlaylists: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylists"];
                };
            };
        };
    };
    createPlaylist: {
        parameters: {
            query: {
                /** @description Playlist title. */
                title: string;
                /** @description Playlist type (video, audio, photo). */
                type: "video" | "audio" | "photo";
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylists"];
                };
            };
        };
    };
    getPlaylistItems: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the playlist. */
                playlistKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylistItems"];
                };
            };
        };
    };
    addPlaylistItems: {
        parameters: {
            query: {
                /** @description Item URI to add. */
                uri: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the playlist. */
                playlistKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylistItems"];
                };
            };
        };
    };
    searchHubs: {
        parameters: {
            query: {
                /** @description Search query string. */
                query: string;
                /** @description Maximum results per hub. */
                limit?: number;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
    getMyPlexAccount: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerAccount"];
                };
            };
        };
    };
    getAccounts: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerAccounts"];
                };
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPreferences"];
                };
            };
        };
    };
    sendSystemNotification: {
        parameters: {
            query: {
                /** @description Notification text. */
                text: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStatistics: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerStatistics"];
                };
            };
        };
    };
    getSessionHistory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerSessionHistory"];
                };
            };
        };
    };
    terminateSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The session key. */
                sessionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session terminated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOnDeck: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getRecentlyAdded: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getLibraryCollections: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getLibraryNewest: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getLibraryUnwatched: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getLibraryFolder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getLibraryFirstCharacter: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getLibrarySectionPreferences: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPreferences"];
                };
            };
        };
    };
    setLibrarySectionPreferences: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferences updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSectionOnDeck: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getSectionRecentlyAdded: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    deleteLibrarySection: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library section deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMetadataTree: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerMetadataChildren"];
                };
            };
        };
    };
    getMetadataPosters: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerImages"];
                };
            };
        };
    };
    getMetadataArts: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerImages"];
                };
            };
        };
    };
    getMetadataSimilar: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerLibraryItems"];
                };
            };
        };
    };
    getMetadataBanner: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The rating key of the item. */
                ratingKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Banner image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLibraryPart: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the media part. */
                partKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerParts"];
                };
            };
        };
    };
    updatePlaylist: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the playlist. */
                playlistKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylists"];
                };
            };
        };
    };
    deletePlaylist: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the playlist. */
                playlistKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removePlaylistItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the playlist. */
                playlistKey: string;
                /** @description The key of the playlist item. */
                itemKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerPlaylistItems"];
                };
            };
        };
    };
    searchSectionHubs: {
        parameters: {
            query: {
                /** @description Search query string. */
                query: string;
                /** @description Maximum results per hub. */
                limit?: number;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The key of the library section. */
                sectionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
    getPromotedHubs: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
    getHomeHubs: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerHub"];
                };
            };
        };
    };
    transcodePhoto: {
        parameters: {
            query: {
                /** @description Photo URL to transcode. */
                url: string;
                /** @description Target width. */
                width?: number;
                /** @description Target height. */
                height?: number;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcoded image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTranscodeDecision: {
        parameters: {
            query?: {
                /** @description Has media decision engine data. */
                hasMDE?: 0 | 1;
                /** @description Media path. */
                path?: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerTranscodeDecision"];
                };
            };
        };
    };
    getTranscodeSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path: {
                /** @description The transcode session ID. */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerTranscodeSession"];
                };
            };
        };
    };
    postTimeline: {
        parameters: {
            query: {
                /** @description Rating key of the item. */
                ratingKey: string;
                /** @description Playback state. */
                state: "playing" | "paused" | "stopped";
                /** @description Current playback position in milliseconds. */
                time: number;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scrobble: {
        parameters: {
            query: {
                /** @description Rating key of the item. */
                ratingKey: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item scrobbled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unscrobble: {
        parameters: {
            query: {
                /** @description Rating key of the item. */
                ratingKey: string;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item unscrobbled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postProgress: {
        parameters: {
            query: {
                /** @description Rating key of the item. */
                ratingKey: string;
                /** @description Progress position in milliseconds. */
                time: number;
            };
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSyncItems: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaContainerSyncItems"];
                };
            };
        };
    };
    refreshSync: {
        parameters: {
            query?: never;
            header?: {
                /** @description Request JSON responses by setting `application/json`. Plex defaults to XML when omitted. */
                Accept?: components["parameters"]["AcceptHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync refresh triggered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
